### ISSUE TITLE
Create an events heatmap view at /admin/events/map

### ISSUE THREAD

**Issue by jlegrone** [Bernie-2016/ground-control#370]

**Comment by saikat** [comment]
I wonder if a heatmap is actually useful here since we have few enough events that map.berniesanders.com gives a pretty good idea of where the density is.  maybe if the heatmap was for all events ever made or if there was a way for us to see events over time or something. 

Alex Coventry made an event aggregation API at some point that was power a set of event dashboards at https://organize.berniesanders.com/volunteer-dashboard/ but it seems to not be working.  But both those projects are open source and under the Bernie-2016 github account if you want to check them out.

**Comment by jlegrone** [comment]
I'll check those out. The main advantage here, I think, is that we could visualize private and unapproved events as well as public, and build in other views like choropleth maps later as well. Sounds like it might be more advantageous to integrate with existing tools though.

**Comment by saikat** [comment]
Eh I think the existing tools have been neglected, but there may be code
there that is useful.  I also think the existing tools didn't have the
benefit of having all the data in a central database, so they are more
complex.  But @rapicastiilo's visualizations at least are worth looking at,
he's really good at that kind of thing.

**Comment by jlegrone** [comment]
Not going to work on this for now.
