### ISSUE TITLE
Marry ground-control login credentials to BSD user credentials

### ISSUE THREAD

**Issue by jlegrone** [Bernie-2016/ground-control#454]
The way this can work is to use the BSD check credentials feature of the api to see if new user accounts are using the same email and password as a BSD account. 

- [ ] If BSD constituent does not exist, create a new BSD constituent AND ground-control user with those credentials
- [ ] If same credentials, create a new ground-control user with those credentials
- [ ] If account credentials are correct but the password for ground-control is incorrect, update the ground-control password and log in
- [ ] If BSD credentials are incorrect, give error message with a link to reset password via BSD

This should also take care of #118

**Comment by jlegrone** [comment]
This would have the side effect of requiring current users whose ground-control password does not match the password for the BSD constituent associated with their email address to log in again with the BSD password, or to do a password reset in BSD.

**Comment by saikat** [comment]
Yeah I actually had it implemented this way and then we stopped.  I think
the migration here may be too much of a headache.  Since ground control has
no separate sign up process, why aren't people just able to use their BSD
passwords on ground control already when signing up?

**Comment by jlegrone** [comment]
@saikat What would the migration headache be, other than my comment above?

People *are* able to log in with their BSD credentials right now, but by not verifying that they have BSD access to the account with that email address, we open up a security issue where ground-control users can take actions on BSD events for that account, like doing voter turnout for their events, as well as any future actions we implement.

Since host email is in a lot of cases fairly easy to guess, I see this as being pretty important. Especially if we ever add anything more than event turnout to ground-control.

**Comment by saikat** [comment]
Yeah, agreed.  Migration headache is the one you pointed out.  Agreed it
could be bad if we add more capabilities -- just not sure how important it
should be now given how much other stuff we have on our plate.  I guess I'm
thinking about this currently on a "next few months" horizon.  I'm not sure
what we would add that would make this a big deal and am tempted to say we
improve this when we get to that point.

**Comment by jlegrone** [comment]
The migration concern is definitely not trivial, but it is restricted to a subset of users who

A) Have both a BSD and ground-control account, and
B) Did not create their ground-control account with the same credentials as their BSD account

The experience they'll have when they attempt to log in to ground-control with their old credentials will be the same as the experience they'll have when they attempt to log in to anywhere else on berniesanders.com with those credentials.

By requiring an updated password for that set of users, we get the advantage of the better user experience across berniesanders.com, offloading of password reset concerns, and the elimination of those security worries as we add features in the future.

**Comment by saikat** [comment]
So as some background, the reason we originally decided not to go down the
route of relying on BSD for login was we were not sure BSD would be able to
handle the load on the API if we ever actually grew a lot.  This was more
of a concern when we were talking about using ground control for voter
turnout as well.  I had a conversation with a guy who had worked with the
BSD API for Obama '12 who had some bad experiences of people getting locked
out of their account when their app exploded in size.

However, I don't think we've had much trouble with the BSD API this time
around so maybe this is ok.  One other thing to consider is when the
campaign ends in November, if we want to continue using Ground Control to,
say, try to push other progressive causes, all of our users will lose
access to their account unless we also store their passwords in Ground
Control.  If we double store the passwords, password reset is going to be
double the work.

I'm not saying this is a bad idea, I'm just not sure it's completely
necessary right now and that a lot of the other issues we currently have
listed are higher priority.  The user experience concern is the one I think
I care more about, but I don't think there is any friction currently.  I
also have not yet heard of any cases of anyone being locked out of Ground
Control because someone else made an account using their e-mail address.
